name: Reproduce Flaky Tests

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          
      # - name: maven clean install 
      #   run: mvn clean install -Dcheckstyle.skip -Drat.skip -U
        
      # - name: Compile Module
      #   run: mvn test-compile -am -Dcheckstyle.skip -Drat.skip -U
      - name: Check
        uses: actions/checkout@v3
        with:
          ref: 2b19a5e026bad97ce4eab0c3353cfcb4ca6361b8
  
      - name: Test with Maven 
        run: | 
              for i in {1..5}; do mvn test -pl jena-text-es -am -Dtest=org.apache.jena.query.text.es.it.TextIndexESIT -DfailIfNoTests=false -Drat.skip -fae; done#>>test_log_DOXIATOOLS-64.txt || echo "Test iteration $i failed">>test_log_DOXIATOOLS-64.txt; done
              
      # - name: Upload Test Log 
      #   if: always() 
      #   uses: actions/upload-artifact@v2 
      #   with: 
      #     name: test_log_DOXIATOOLS-64
      #     path: test_log_DOXIATOOLS-64.txt
